feat(AddProblemCardPreview): add preview problem card
taskany-inc/hire pull request #1035
Opened 2024-09-24 09:01 UTC by Katrin-kudryash

## PR includes

-   [ ] Refactor
-   [ ] Feature

## Related issues

Resolve #963

2024-09-26 10:45 UTC, Katrin-kudryash commented
![s](https://github.com/user-attachments/assets/ac509a7a-3b3d-473f-b0c3-b0805e5bd778)

2024-09-26 10:46 UTC, Katrin-kudryash commented
Uploading a.mov…

2024-09-26 10:46 UTC, Katrin-kudryash commented
https://github.com/user-attachments/assets/6eee90b2-66cf-4214-9264-b7ff6c61df39

2024-09-26 13:40 UTC, Katrin-kudryash commented
https://github.com/user-attachments/assets/92c8dd83-9626-4365-aea1-34c9b2219f61

2024-09-30 14:20 UTC, Katrin-kudryash commented
https://github.com/user-attachments/assets/bf64ebc2-6e7a-4e03-84d1-50ca64f8b0c9

2024-10-01 10:05 UTC, tsumo requested changes

2024-10-01 10:05 UTC, tsumo commented on src/components/AddProblemToSection/AddProblemToSection.tsx
> +        interviewId?: number;
interviewId and sectionId should not be optional, since problemPreview is already optional

2024-10-01 10:05 UTC, tsumo commented on src/components/Section/Section.tsx
> +    visiblePreviewProblem?: boolean;
showAddProblemButton

2024-10-01 10:05 UTC, tsumo commented on src/components/ProblemPreview/ProblemPreview.tsx
> +export const ProblemPreview: FC<ProblemPreviewProps> = ({ problemPreview }: ProblemPreviewProps) => {
This is not a preview of a problem. Why this component is separate from AddProblemToSection?

2024-10-01 14:32 UTC, tsumo requested changes

2024-10-01 14:32 UTC, tsumo commented on src/components/AddProblemToSectionPreview/AddProblemToSectionPreview.tsx
> +export const ProblemPreview: FC<ProblemPreviewProps> = ({ problemPreview }: ProblemPreviewProps) => {
Old component name

2024-10-01 14:32 UTC, tsumo commented on src/components/AddProblemToSectionPreview/AddProblemToSectionPreview.tsx
> +        interviewId?: number;
Optional inside optional

2024-10-01 14:32 UTC, tsumo commented on src/components/ProblemList/ProblemList.tsx
> +    problemPreview?: {
don't need to wrap ids inside object in this component

2024-10-01 14:32 UTC, tsumo commented on src/components/SectionFeedback/SectionFeedback.i18n/ru.json
> +    "Add problem": ""
translation missing

2024-10-01 14:32 UTC, tsumo commented on src/contexts/previewContext.tsx
> +    showProblemPreview: (params: { interviewId?: number; sectionId?: number }) => void;
showAddProblemToSectionPreview

2024-10-01 14:32 UTC, tsumo commented on src/contexts/previewContext.tsx
> +        interviewId?: number;
Optional type inside optional type

2024-10-02 11:44 UTC, tsumo requested changes

2024-10-02 11:44 UTC, tsumo commented on src/contexts/previewContext.tsx
> +    showAddProblemToSectionPreview: (params: { interviewId?: number; sectionId?: number }) => void;
These also don't need to be optional

2024-10-02 13:43 UTC, tsumo approved these changes

2024-10-02 13:55 UTC, merged