fix: can't edit calendar slot in section
taskany-inc/hire pull request #1065
Opened 2024-10-04 09:40 UTC by IgorGoryany

## PR includes

-   [x] Bug Fix

## Related issues

Resolve #1061

2024-10-04 12:14 UTC, tsumo commented on src/components/CreateOrUpdateSectionForm/CreateOrUpdateSectionForm.tsx
> +    calendarSlotId: z.string().nullish(),
calendarSlot and calendarSlotId in the same schema?

2024-10-09 07:13 UTC, tsumo requested changes
Applied migration cannot be deleted

2024-10-14 08:06 UTC, tsumo requested changes

2024-10-14 08:06 UTC, tsumo commented on src/components/CreateOrUpdateSectionForm/CreateOrUpdateSectionForm.tsx
> +    calendarSlotId: z.string().nullish(),
I think it's the same as `calendarSlot.exceptionId`

2024-10-17 07:26 UTC, tsumo requested changes

2024-10-18 09:39 UTC, tsumo approved these changes

2024-10-21 12:06 UTC, asabotovich approved these changes

2024-10-21 13:20 UTC, merged