History of change in section preview
taskany-inc/hire pull request #1082
Opened 2024-10-11 09:58 UTC by Katrin-kudryash

## PR includes

-   [ ] Refactor
-   [ ] Feature

## Related issues

Resolve #1062

2024-10-14 08:13 UTC, tsumo requested changes
Please delete SectionHistoryPage

2024-10-16 11:47 UTC, tsumo requested changes
Also `pageHrefs.interviewSectionHistory` is not needed anymore

2024-10-16 11:47 UTC, tsumo commented on src/pages/interviews/[interviewId]/sections/[sectionId]/history.tsx
> -import { SectionHistoryPage } from '../../../../../components/SectionHistoryPage/SectionHistoryPage';
This file is also can be deleted

2024-10-17 06:38 UTC, tsumo commented
> Also `pageHrefs.interviewSectionHistory` is not needed anymore

@Katrin-kudryash

2024-10-17 11:44 UTC, asabotovich approved these changes

2024-10-17 11:52 UTC, merged