Confirmation fixes
taskany-inc/hire pull request #318
Opened 2023-11-08 12:42 UTC by Katrin-kudryash

## PR includes

-   [ ] Bug Fix

## Related issues

Resolve #315

2023-11-08 12:42 UTC, Katrin-kudryash commented
<img width="572" alt="Untitled" src="https://github.com/taskany-inc/hire/assets/81121562/50b01a38-bcef-46bc-a922-dcdb8520a56c">

2023-11-08 12:45 UTC, Katrin-kudryash commented
<img width="612" alt="Untitled" src="https://github.com/taskany-inc/hire/assets/81121562/226d3700-186f-4e7b-a1f9-6b8ea12e8a00">

2023-11-08 13:47 UTC, tsumo requested changes

2023-11-08 13:47 UTC, tsumo commented on src/components/Confirmation.tsx
> +const StyledModalContent = styled(ModalContent)`
Maybe simple div will work? Otherwise we put ModalContent inside ModalContent

2023-11-08 13:47 UTC, tsumo commented on src/components/Confirmation.tsx
> +                <Button onClick={onClose} style={{ marginLeft: gapS }} text={tr('Cancel')} />
flex and gap on the container will be better than inline margin

2023-11-08 14:57 UTC, tsumo approved these changes

2023-11-09 08:03 UTC, 9teen90nine commented
useKeyboard for Enter support?

2023-11-09 10:50 UTC, closed without merging