Delete color-scheme
taskany-inc/hire pull request #320
Opened 2023-11-08 12:58 UTC by Katrin-kudryash

## PR includes

-   [ ] Bug Fix

## Related issues

Resolve #319

2023-11-08 13:49 UTC, tsumo requested changes

2023-11-08 13:49 UTC, tsumo commented on src/components/layout/GlobalStyle.ts
TODO should also be deleted

2023-11-08 14:29 UTC, tsumo approved these changes

2023-11-08 14:33 UTC, nyet-ty approved these changes

2023-11-09 08:03 UTC, 9teen90nine approved these changes

2023-11-09 09:05 UTC, merged