Allow adding description to section of any type
taskany-inc/hire pull request #385
Opened 2023-11-23 09:24 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

## Related issues

Resolve #360

2023-11-23 16:00 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/hire/assets/81121562/74e4a7e4-249e-4b32-a402-b20863ef1961

2023-11-24 08:40 UTC, tsumo requested changes

2023-11-24 08:40 UTC, tsumo commented on src/components/CreateOrUpdateSectionForm/CreateOrUpdateSectionForm.tsx
> +                            <FormInput
Can we change it to text area?

2023-11-24 08:40 UTC, tsumo commented on src/components/CreateOrUpdateSectionForm/CreateOrUpdateSectionForm.tsx
> +                                        : tr('Add a link to jazz or a couple of notes')
ссылку на встречу / link to a meeting

2023-11-24 09:08 UTC, nyet-ty commented on src/components/CreateOrUpdateSectionForm/CreateOrUpdateSectionForm.tsx
> +                            <FormInput
+

2023-11-24 10:57 UTC, Katrin-kudryash commented
<img width="712" alt="Untitled 7" src="https://github.com/taskany-inc/hire/assets/81121562/e2e3cfdd-e0e6-45ba-98ad-3072bb886118">
<img width="714" alt="Untitled 8" src="https://github.com/taskany-inc/hire/assets/81121562/8c8aaa53-c92a-4dab-a657-3912cc012f74">

2023-11-24 11:06 UTC, nyet-ty commented on src/components/CreateOrUpdateSectionForm/CreateOrUpdateSectionForm.i18n/ru.json
> +    "In which team is the product final held?": "",
I think you missed translation here

2023-11-24 11:07 UTC, nyet-ty approved these changes

2023-11-24 11:10 UTC, tsumo requested changes
```
Check warning on line 113 in src/components/CreateOrUpdateSectionForm/CreateOrUpdateSectionForm.tsx

React Hook useCallback has a missing dependency: 'schedulable'. Either include it or remove the dependency array
```

2023-11-24 11:17 UTC, tsumo approved these changes

2023-11-24 11:21 UTC, merged