fix(ProblemPage): fix history display
taskany-inc/hire pull request #421
Opened 2023-12-15 08:25 UTC by Katrin-kudryash

## PR includes

-   [ ] Bug Fix

## Related issues

Resolve #419

2023-12-15 08:27 UTC, Katrin-kudryash commented
<img width="1791" alt="Untitled 11" src="https://github.com/taskany-inc/hire/assets/81121562/6ae32cd7-f712-44ef-bde7-ba21c4a355d7">

2023-12-15 08:27 UTC, Katrin-kudryash commented
<img width="1790" alt="Untitled 15" src="https://github.com/taskany-inc/hire/assets/81121562/dedd0d54-564e-4ad7-a862-ae5c924ef9e7">

2023-12-15 08:44 UTC, nyet-ty approved these changes

2023-12-15 09:17 UTC, 9teen90nine commented on src/components/ProblemHistoryCard/ProblemHistoryCard.tsx
> +    max-width: 650px;
let's make it a bit wider, like 1000px or so

2023-12-18 14:53 UTC, Katrin-kudryash commented
<img width="1234" alt="Untitled 4" src="https://github.com/taskany-inc/hire/assets/81121562/866d8d7f-1610-4d7d-adcd-67124e61c3ec">

2023-12-18 14:56 UTC, tsumo requested changes

2023-12-18 14:56 UTC, tsumo commented on src/components/Problem/Problem.tsx
> +            {problem.problemHistory.length > 0 && (
Nullable can also check for zero

2023-12-19 07:15 UTC, tsumo approved these changes

2023-12-19 08:08 UTC, 9teen90nine approved these changes

2023-12-19 08:09 UTC, merged