Send ical events if section interviewer changes
taskany-inc/hire pull request #479
Opened 2024-01-11 20:41 UTC by nyet-ty

Resolve #461

## PR includes

-   [ ] Feature

2024-01-11 21:10 UTC, tsumo commented on src/modules/emaiMethods.ts
> +import RRule from 'rrule';
Default imports from rrule for some reason are always broken on my machine. Only `import { Rrule }` works

2024-01-12 08:33 UTC, tsumo approved these changes

2024-01-12 14:56 UTC, 9teen90nine commented on src/modules/emaiMethods.ts
> +        console.log('exclude', exclude);
you left debug

2024-01-15 08:24 UTC, 9teen90nine requested changes

2024-01-15 08:24 UTC, 9teen90nine commented on src/modules/emailMethods.ts
> +        from: 'Taskany Hire',
you have copypaste 'from' and other fields. Make a wrapper function with default values.

2024-01-15 08:24 UTC, 9teen90nine commented on src/modules/emailMethods.ts
> +        from: 'Hire',
here too

2024-01-16 10:24 UTC, 9teen90nine commented on src/modules/nodemailer.ts
> +const message = ({ from = 'Hire', to, subject, text, html, icalEvent }: MessageBody) => ({
Taskany Hire?

2024-01-16 10:24 UTC, 9teen90nine approved these changes

2024-01-16 10:25 UTC, merged