HR Filter in candidates
taskany-inc/hire pull request #526
Opened 2024-01-29 15:28 UTC by nyet-ty

Resolve #515 

## PR includes

-   [x] Feature

2024-01-29 17:22 UTC, tsumo requested changes

2024-01-29 17:22 UTC, tsumo commented on src/components/CandidateFilterApplied/CandidateFilterApplied.i18n/ru.json
> +    "Hrs: ": "Эйчар: "
Better leave that without translation

2024-01-30 08:05 UTC, tsumo approved these changes

2024-01-30 08:50 UTC, 9teen90nine approved these changes

2024-01-30 08:50 UTC, 9teen90nine commented on src/components/CandidateFilterBar/CandidateFilterBar.i18n/en.json
> +    "Hrs": "",
HR's?

2024-01-30 08:59 UTC, merged