Vacancy list page
taskany-inc/hire pull request #558
Opened 2024-02-15 18:52 UTC by tsumo

## PR includes

-   [x] Feature

## Related issues

Resolve #553

<img width="716" alt="Screenshot 2024-02-15 at 21 52 02" src="https://github.com/taskany-inc/hire/assets/4553070/386dcee8-325e-46e9-95be-21d3f7fa0f6c">

2024-02-16 17:27 UTC, awinogradov requested changes

2024-02-16 17:27 UTC, awinogradov commented on src/components/VacancyCard/VacancyCard.tsx
> +                        HR: {vacancy.hr.name}
i18n

2024-02-16 17:27 UTC, awinogradov commented on src/hooks/useHeaderMenu.ts
> +        const canReadVacancies = accessChecks.vacancy.read(session).allowed;
U can inline it into if statement

2024-02-16 17:27 UTC, awinogradov commented on src/modules/crewTypes.ts
> +    ON_HOLD = 'ON_HOLD',
U can remove `ON_` prefix. 

<img width="900" alt="image" src="https://github.com/taskany-inc/hire/assets/982072/403677a9-5af8-411e-9674-0f2254842924">

2024-02-16 18:56 UTC, tsumo commented on src/components/VacancyCard/VacancyCard.tsx
> +                        HR: {vacancy.hr.name}
Кадровик? :)

2024-02-16 19:00 UTC, awinogradov commented on src/components/VacancyCard/VacancyCard.tsx
> +                        HR: {vacancy.hr.name}
Рекрутер) Читается как рекрутЭр

2024-02-19 10:08 UTC, 9teen90nine approved these changes

2024-02-20 09:46 UTC, awinogradov approved these changes

2024-02-20 12:44 UTC, merged