Unfinished solutions warning
taskany-inc/hire pull request #646
Opened 2024-03-22 11:07 UTC by nyet-ty

Resolve #631

## PR includes

-   [x] Feature

2024-03-22 11:45 UTC, tsumo commented
screenshot please

2024-03-22 12:50 UTC, nyet-ty commented
<img width="698" alt="image" src="https://github.com/taskany-inc/hire/assets/61706821/3df4d0c8-ac10-4ac5-9b6c-48dc6f8f34e2">

2024-03-22 15:50 UTC, nyet-ty commented
<img width="698" alt="image" src="https://github.com/taskany-inc/hire/assets/61706821/bb78d070-a8e7-4153-a4d2-e32220930ca6">

2024-03-22 17:00 UTC, nyet-ty commented
![image](https://github.com/taskany-inc/hire/assets/61706821/c729858e-0854-4f0b-8283-5fd6b36ca9b7)

2024-03-22 17:32 UTC, 9teen90nine requested changes

2024-03-22 17:32 UTC, 9teen90nine commented on src/components/SectionFeedback/SectionFeedback.tsx
> +        return rec.result === 'UNKNOWN' ? [...acc, rec.problem.name] : acc;
acc.push is much faster

2024-03-22 18:22 UTC, tsumo approved these changes

2024-03-25 10:52 UTC, 9teen90nine approved these changes

2024-03-25 10:52 UTC, merged