Problem comment reactions
taskany-inc/hire pull request #721
Opened 2024-05-15 15:46 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

## Related issues

Resolve #452

2024-05-20 08:49 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/hire/assets/81121562/3eddc80c-4a6c-4d8b-a2ee-91bf58086f4b

2024-05-20 13:25 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/hire/assets/81121562/96056e72-f366-489a-8870-459a17e3969a

2024-05-20 13:28 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/hire/assets/81121562/4b49168e-51c3-461b-af22-f5c417335e63

2024-05-22 07:45 UTC, tsumo requested changes

2024-05-22 07:45 UTC, tsumo commented on src/modules/problemMethods.ts
> +    const comments = problem?.comments.map((comment) => {
comment formatting could be moved to utils

2024-05-22 07:45 UTC, tsumo commented on src/utils/pageContext.ts
> +export const pageContext = React.createContext<PageContext>({ theme: 'dark', themeId: 0, ssrTime: 0 });
This context is not rendered anywhere, it will not work

Better to do this in separate issue

2024-05-23 12:17 UTC, tsumo approved these changes

2024-05-23 12:19 UTC, 9teen90nine approved these changes

2024-05-23 12:35 UTC, merged