Join timeline with sections
taskany-inc/hire pull request #733
Opened 2024-06-03 08:46 UTC by Katrin-kudryash

## PR includes

-   [x] Feature

## Related issues

Resolve #722

2024-06-03 12:27 UTC, asabotovich commented on src/components/InterviewSectionListItem.tsx
> +    className?: string;
we can replace this with `extends HTMLAttributes<HTMLDivElement>`

2024-06-03 12:27 UTC, asabotovich commented on src/components/CardHeaderSection.tsx
> +`;
why do we use styled in new components?

2024-06-03 12:27 UTC, asabotovich commented on src/components/CardHeaderSection.tsx
> +                <>
remove fragment

2024-06-03 12:27 UTC, asabotovich commented on src/components/CardHeaderSection.tsx
> +    interview: Interview & { candidateSelectedSectionId: number | null };
InterviewWithRelations ? (like in InterviewSectionListItem?)

2024-06-03 12:48 UTC, tsumo requested changes

2024-06-03 12:48 UTC, tsumo commented on src/components/Interview/Interview.tsx
> +                <StyledTitle size="xl">Activity Feed</StyledTitle>
translation

2024-06-03 12:48 UTC, tsumo commented on src/modules/interviewTypes.ts
> +    sections: SectionWithSectionTypeAndInterviewerAndSolutionsRelations[]; // TODO: remove??
Why remove them? You still need them to construct activity feed

2024-06-03 12:48 UTC, tsumo commented on src/modules/interviewTypes.ts
> +    comments: CommentWithUserAndReaction[] | undefined; // TODO: remove ??
same

2024-06-05 11:54 UTC, Katrin-kudryash commented
<img width="698" alt="Untitled 3" src="https://github.com/taskany-inc/hire/assets/81121562/76bbfb98-31f0-4146-bbab-4fcc03eed04a">

2024-06-05 14:03 UTC, Katrin-kudryash commented
<img width="635" alt="Untitled 3" src="https://github.com/taskany-inc/hire/assets/81121562/193b0826-3456-40c1-a750-fe5a6065d26e">
<img width="668" alt="Untitled 4" src="https://github.com/taskany-inc/hire/assets/81121562/93f15bc2-d281-4c22-b621-fca6baf603df">

2024-06-05 16:46 UTC, Katrin-kudryash commented
<img width="662" alt="Untitled 4" src="https://github.com/taskany-inc/hire/assets/81121562/9d0818e1-21f3-4b0a-b3be-58abe7cb5d93">
<img width="665" alt="Untitled 3" src="https://github.com/taskany-inc/hire/assets/81121562/4aaf5cc3-04eb-4133-9ca1-8b6b2c45643b">

2024-06-06 09:28 UTC, tsumo approved these changes

2024-06-06 10:00 UTC, asabotovich commented on src/components/Interview/Interview.tsx
> +                        interview.activityFeed.map((item) =>
use nullable

2024-06-06 10:00 UTC, asabotovich commented on src/components/InterviewSectionListItem.tsx
> +    };
You can keep out of component

2024-06-06 10:59 UTC, asabotovich approved these changes

2024-06-06 11:00 UTC, merged