Status update comments
taskany-inc/hire pull request #749
Opened 2024-06-14 09:07 UTC by Katrin-kudryash

## PR includes

-   [x] Feature

## Related issues
Resolve #723

2024-07-01 12:21 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/hire/assets/81121562/e1535b0c-43d0-4e1a-8072-323eb2bf4ccd

2024-07-01 12:22 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/hire/assets/81121562/a6c12afb-159e-43e5-8d30-fb330f0444b6

2024-07-01 13:00 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/hire/assets/81121562/5b6786c5-18c6-4f4e-b65c-1dd99ed3b82a

2024-07-01 14:37 UTC, nyet-ty requested changes

2024-07-01 14:37 UTC, nyet-ty commented on prisma/schema.prisma
> +  status InterviewStatus? @default(NEW)
do we need default status if it optional for comment?

2024-07-01 15:59 UTC, tsumo requested changes

2024-07-01 15:59 UTC, tsumo commented on src/components/CommentCreateForm/CommentCreateForm.tsx
> +    statusDropdown?: React.ReactNode;
Unused prop?

2024-07-01 15:59 UTC, tsumo commented on src/components/CommentCreateForm/CommentCreateForm.tsx
> +    }, [rejectReasons]);
Missing dependancy

2024-07-01 15:59 UTC, tsumo commented on src/components/CommentCreateForm/CommentCreateForm.tsx
> +        const items: DropdownMenuItem[] = [];
Just return array directly here `return [ {}, {}, ]`

2024-07-01 15:59 UTC, tsumo commented on src/components/CommentCreateForm/CommentCreateForm.tsx
> +                    visibleRejectOption && (
nullable

2024-07-01 15:59 UTC, tsumo commented on src/components/CommentForm/CommentForm.tsx
> +    childrenProps?: React.ReactNode;
Looks like you dont need this prop, you can move RejectInterviewStatus into this component

2024-07-01 15:59 UTC, tsumo commented on src/components/CommentForm/CommentForm.module.css
> +.CommentFormRejectInterviewStatusWrapper {
Does this css really do anything?

2024-07-01 15:59 UTC, tsumo commented on src/components/CommentView/CommentView.i18n/en.json
> +    "Status interview: ": ""
Interview status

2024-07-01 15:59 UTC, tsumo commented on src/components/CommentView/CommentView.tsx
> +                        <CardInfo className={cn(s.CardInfo, InterviewStatusColors[interviewStatusChip])}>
looks heavy, maybe move this to a new component InterviewStatusCommentCard?

2024-07-01 15:59 UTC, tsumo commented on src/components/RejectInterviewStatus/RejectInterviewStatus.tsx
> +export const RejectInterviewStatus = ({
InterviewRejectReasonDropdown

2024-07-01 15:59 UTC, tsumo commented on src/trpc/routers/commentRouter.ts
> +                const interview = await interviewMethods.getById(input.target.interviewId);
don't need this, get interviewWithSections(input.target.interviewId)

2024-07-02 13:32 UTC, tsumo approved these changes

2024-07-02 14:50 UTC, nyet-ty approved these changes

2024-07-02 15:04 UTC, merged