#770
taskany-inc/hire pull request #772
Opened 2024-07-01 18:24 UTC by nyet-ty

Resolve #770

2024-07-02 07:43 UTC, tsumo requested changes

2024-07-02 07:43 UTC, tsumo commented on src/trpc/routers/sectionsRouter.ts
>      await crewMethods.giveAchievement({
lets log the result of the request

2024-07-02 21:46 UTC, tsumo approved these changes

2024-07-04 08:45 UTC, 9teen90nine approved these changes

2024-07-04 10:41 UTC, merged