SectionFeedback from harmony
taskany-inc/hire pull request #786
Opened 2024-07-09 10:55 UTC by Katrin-kudryash

## PR includes

-   [ ] Refactor
-   [ ] Feature

## Related issues

Resolve #775

2024-07-11 08:50 UTC, tsumo requested changes

2024-07-11 08:50 UTC, tsumo commented on src/components/AddProblemToSection/AddProblemToSection.module.css
> +.CommentFormWrapper {
looks like only first class in the file is used

2024-07-11 17:31 UTC, tsumo commented on src/components/AddProblemToSection/AddProblemToSection.module.css
> +.CommentFormWrapper {
Still unused classes

2024-07-12 10:09 UTC, tsumo approved these changes

2024-07-15 18:37 UTC, nyet-ty approved these changes

2024-07-15 18:40 UTC, merged