New filter bar for analytics page
taskany-inc/hire pull request #796
Opened 2024-07-16 21:54 UTC by IgorGoryany

## PR includes

-   [x] Refactor

## Related issues

Resolve #794

## QA Instructions, Screenshots, Recordings

2024-07-16 22:05 UTC, IgorGoryany commented
**Input has been removed**

2024-07-18 15:41 UTC, 9teen90nine requested changes

2024-07-18 15:41 UTC, 9teen90nine commented on src/components/AnalyticsFilterMenuBar/AnalyticsFilterMenuBar.tsx
> +    }, []);
yo, even github is against that

2024-07-22 10:41 UTC, tsumo requested changes

2024-07-22 10:41 UTC, tsumo commented on src/components/AnalyticsFilterMenuBar/AnalyticsFilterMenuBar.tsx
> +    const period = tr((hasPeriodBeenSelected ? periodFilter : periodTitle) as I18nKey);
Should use map
```
const period = {
  period: tr('period'),
  title: tr('title'),
}[hasPeriodBeenSelected ? periodFilter : periodTitle]
```

2024-07-29 09:37 UTC, tsumo requested changes

2024-07-29 09:37 UTC, tsumo commented on src/components/AnalyticsFilterApplied/AnalyticsFilterApplied.tsx
> +const StyledApplied = styled(FiltersApplied)`
Let's avoid styled in new components

2024-07-29 09:37 UTC, tsumo commented on src/components/AnalyticsFilterMenuBar/AnalyticsFilterMenuBar.tsx
> +const periodMap: Record<PeriodMapKey, string> = {
tr should be called inside component render, otherwise dynamic langauge change won't work

2024-07-29 09:37 UTC, tsumo commented on src/components/AnalyticsFilterMenuBar/AnalyticsFilterMenuBar.tsx
> +    const [periodFilter, setPeriodFFilter] = useState<I18nKey>(periodTitle as I18nKey);
maybe `PeriodMapKey` instead of `I18Key`?

2024-07-30 10:46 UTC, tsumo approved these changes

2024-07-31 07:33 UTC, 9teen90nine approved these changes

2024-07-31 07:34 UTC, merged