Button from harmony
taskany-inc/hire pull request #834
Opened 2024-07-31 15:26 UTC by IgorGoryany

## PR includes

-   [x] Refactor

## Related issues

Resolve #828

## QA Instructions, Screenshots, Recordings

2024-08-01 11:14 UTC, tsumo requested changes

2024-08-01 11:14 UTC, tsumo commented on scripts/refactoring/harmonyButtons.ts
> +import { Project, SyntaxKind } from 'ts-morph';
Don't really need this in repo, it's a one-time operation

2024-08-06 17:13 UTC, tsumo requested changes
package-lock has unnecessary changes from ts-morph

2024-08-08 13:18 UTC, nyet-ty approved these changes

2024-08-08 13:36 UTC, tsumo approved these changes

2024-08-08 14:50 UTC, closed without merging