Calendar page has horizontal scroll
taskany-inc/hire pull request #907
Opened 2024-08-15 09:08 UTC by Katrin-kudryash

## PR includes

-   [ ] Bug Fix

## Related issues

Resolve #874

2024-08-16 10:43 UTC, tsumo requested changes

2024-08-16 10:43 UTC, tsumo commented on src/components/LayoutMain/LayoutMain.module.css
> +    height: 100vh;
Why? Scroll already works as expected

2024-08-16 14:22 UTC, tsumo requested changes

2024-08-16 14:22 UTC, tsumo commented on src/components/LayoutMain/LayoutMain.module.css
> +    overflow: auto;
Why?

2024-08-16 14:22 UTC, tsumo commented on src/components/PageHeader/PageHeader.module.css
> +  height: 2.5rem;
Why removing sticky from header?

2024-08-19 14:04 UTC, tsumo approved these changes

2024-08-19 14:19 UTC, asabotovich approved these changes

2024-08-19 14:23 UTC, merged