Role popup is not fully visible and dropdown big in hire streams
taskany-inc/hire pull request #914
Opened 2024-08-16 12:34 UTC by Katrin-kudryash

## PR includes

-   [ ] Bug Fix

## Related issues

Resolve #908

2024-08-16 14:58 UTC, asabotovich requested changes

2024-08-16 14:58 UTC, asabotovich commented on src/components/CardHeader/CardHeader.module.css
> +}
Where you are going to use it?

2024-08-19 08:52 UTC, tsumo requested changes

2024-08-19 11:29 UTC, asabotovich approved these changes

2024-08-19 11:30 UTC, tsumo approved these changes

2024-08-19 11:48 UTC, merged