Section popups
taskany-inc/hire pull request #929
Opened 2024-08-21 11:23 UTC by Katrin-kudryash

## PR includes

-   [ ] Refactor
-   [ ] Feature

## Related issues

Resolve #802

2024-08-27 08:58 UTC, Katrin-kudryash commented
https://github.com/user-attachments/assets/df90cc81-3680-4fcf-929b-e52496edcc86

2024-08-27 11:00 UTC, asabotovich requested changes

2024-08-27 11:00 UTC, asabotovich commented on src/components/SectionPreview/SectionPreview.tsx
> +};
I think we should have abstract component 
```
<Preview header={<HeaderComponentA />}>
    <ContentComponentA>
</Preview>
```

2024-08-28 13:32 UTC, Katrin-kudryash commented on src/components/SectionPreview/SectionPreview.tsx
> +        <>
no
![Untitled 2](https://github.com/user-attachments/assets/dd246561-1bb4-45f0-9926-1c35f8e1d339)

2024-08-28 14:02 UTC, Katrin-kudryash commented on src/contexts/previewContext.tsx
> +    }, []);
use 2 useMemo in PreviewContext components ?

2024-08-29 12:16 UTC, asabotovich commented on src/components/HeaderPreview/HeaderPreview.tsx
> +                            </Text>
Use component from harmony

2024-08-29 12:16 UTC, asabotovich commented on src/components/HeaderPreview/HeaderPreview.tsx
> +export const HeaderPreview: FC<HeaderPreviewProps> = ({ pageTitle, href, section, date, readOnly }) => {
Section Preview

2024-08-29 12:16 UTC, asabotovich commented on src/components/Section/Section.tsx
> +    visible: boolean;
title: ReactNode

2024-09-02 10:11 UTC, asabotovich commented on src/components/Previews/Previews.tsx
> +        </>
```return nullable(sectionId, (s) => <SectionPreview sectionId={s} />);```

2024-09-16 15:31 UTC, Katrin-kudryash commented
https://github.com/user-attachments/assets/d2157d6f-7de9-4ef9-9286-230247fa9833


https://github.com/user-attachments/assets/d88e2f27-7255-4325-96c1-3a37807931ec

2024-09-17 08:49 UTC, asabotovich approved these changes

2024-09-17 10:58 UTC, tsumo requested changes

2024-09-17 10:58 UTC, tsumo commented on src/components/ProblemList/ProblemList.tsx
> +    interviewId: number;
Problem list is used at the /problems where you don't have any interviews or sections

2024-09-17 13:34 UTC, tsumo requested changes

2024-09-17 13:34 UTC, tsumo commented on src/components/Problems/Problems.tsx
> +        <LayoutMain pageTitle={tr('Problems')} aboveContainer={<ProblemFilterBar />}>
Why filter bar is moved to aboveContainer?

2024-09-17 13:34 UTC, tsumo commented on src/components/SectionHeaderPreview/SectionHeaderPreview.i18n/ru.json
> +    "Candidate": "",
translations

2024-09-17 13:34 UTC, tsumo commented on src/components/SectionPage/SectionPage.i18n/ru.json
> +    "Section with {name} canceled": "Секция отменена по причине",
wrong translation

2024-09-17 15:41 UTC, tsumo requested changes

2024-09-17 15:41 UTC, tsumo commented on src/components/SectionHeaderPreview/SectionHeaderPreview.i18n/ru.json
> +    "Interviewer": "Интервьюер"
Собеседующий

2024-09-17 15:41 UTC, tsumo commented on src/components/Problems/Problems.tsx
> +    const interviewId = parseNumber(router.query.interviewId);
This page doesn't have interviewId and sectionId. Let's rename component to ProblemsPage to make it clear

2024-09-17 15:59 UTC, tsumo requested changes

2024-09-17 15:59 UTC, tsumo commented on src/components/ProblemsPage/ProblemsPage.tsx
> +    const interviewId = parseNumber(router.query.interviewId);
No interviewId and sectionId on this page

2024-09-18 08:46 UTC, tsumo requested changes

2024-09-18 08:46 UTC, tsumo commented on src/components/ProblemsPage/ProblemsPage.tsx
> +    const sectionId = parseNumber(router.query.sectionId);
This page never has sectionId in query

2024-09-18 09:35 UTC, tsumo approved these changes

2024-09-18 09:38 UTC, merged