Remove unnecessary deps
taskany-inc/hire pull request #944
Opened 2024-08-22 14:51 UTC by IgorGoryany

## PR includes

-   [x] Bug Fix

## Related issues

Resolve #869

2024-08-22 15:29 UTC, LamaEats approved these changes

2024-08-22 19:14 UTC, tsumo requested changes

2024-08-22 19:14 UTC, tsumo commented on src/hooks/useHeaderMenu.ts
>  import { useMemo } from 'react';
Rename file please

2024-08-23 10:33 UTC, tsumo approved these changes

2024-08-23 10:43 UTC, merged